version: "3.3"
services:
  # app:
  #   container_name: python_docker
  #   build: ./app/
  db:
    container_name: postgres_docker
    # build: ./database/
    image: postgres:15.1
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_DB=site-sitedatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
